### PR TITLE
Fix package and some tree cleaning

### PR DESCRIPTION
**Pull request by MrDuartePT**
I fix and updated all dev-python packages for python3 and all the url
I was trying to see how to solve ros-melodic but i think we need a script that can solve all the eapi and update the python version to 3.9 to 3.11 and form there we can see what is broken on the meta package of desktop and desktop full (I notice that some desktop_full package are missing).
This probably we apply to the other ros versions.
Sorry for the large commit but i triple check everthing

### CODE REVIEW

**Comment by MrDuartePT** [comment]
It will be a draft for now because i well fix a couple of more things

**Comment by MrDuartePT** [comment]
Also clean tree when package exist in gentoo repo

**Comment by MrDuartePT** [comment]
For now this are good update ans some cleaning of old package that are available in gentoo tree.
what you think @tomkimsour

**Comment by tomkimsour** [comment]
Sorry I completely missed that. If you found a stable solution for you then you should definitly file a PR on the main repository that explains what you did. If some of your work relies on mine, then think about mentioning the one I opened already.

**Comment by MrDuartePT** [comment]
> Sorry I completely missed that. If you found a stable solution for you then you should definitly file a PR on the main repository that explains what you did. If some of your work relies on mine, then think about mentioning the one I opened already.

This is a bit outdated as well I will try to make a PR to the main project when I have a bit more free time but most of the package will need to bump the EAPI and the python version.
But I think is better to focus is the current ROS 2 version and just forget about ROS 1 since is EOL at this point

**Comment by tomkimsour** [comment]
Yes that's a better thing to do i reckon

**Pull request closed without merging**
